### ISSUE TITLE
rest-client version has two open security vulnerabilities

### ISSUE THREAD

**Issue by voxxit** [engineyard/engineyard-cloud-client#15]
Please update the version of rest-client in the gemspec to `~> 1.8.0`. There are two open security vulnerabilities for that gem:
- **OSVDB-119878** - Session fixation vulnerability via Set-Cookie headers - https://github.com/rest-client/rest-client/issues/369
- **OSVDB-117461** - Log plaintext password local disclosure - https://github.com/rest-client/rest-client/issues/349

Thanks!

**Comment by igorbp** [comment]
Updated on #18
